/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: { center: true, padding: '1rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        // ── AgroMarket Green (tierra fértil) ──────────────────────
        'am-green': {
          50:  '#E8F5E6',
          100: '#C8E6C2',
          200: '#A5D4A0',
          300: '#7FC37D',
          400: '#52B44E',
          500: '#2D7D2A',
          600: '#246B21',
          700: '#1A5C38',
          800: '#134820',
          900: '#0D3A1A',
          950: '#07200E',
        },
        // ── AgroMarket Amber (cosecha, valor) ──────────────────────
        'am-amber': {
          50:  '#FEF3DC',
          100: '#FDE3A7',
          200: '#FBD070',
          300: '#F9BC3A',
          400: '#F5A623',
          500: '#E08C0B',
          600: '#B87D0E',
          700: '#8A5A07',
          800: '#5C3C04',
          900: '#2E1E02',
        },
        // ── AgroMarket Earth (naturaleza, confianza) ──────────────
        'am-earth': {
          50:  '#F5EDE6',
          100: '#E7D3C4',
          200: '#D4B59C',
          300: '#BE9372',
          400: '#8B5E3C',
          500: '#6E4A2B',
          600: '#563820',
          700: '#3E2817',
          800: '#28180E',
          900: '#140C07',
        },
        // ── Semantic ────────────────────────────────────────────────
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
      },
      borderRadius: { lg: 'var(--radius)', md: 'calc(var(--radius) - 2px)', sm: 'calc(var(--radius) - 4px)' },
      fontFamily: {
        display: ['var(--font-syne)', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in': { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        'pulse-dot': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-in': 'slide-in 0.3s ease-out',
        'pulse-dot': 'pulse-dot 1.5s ease-in-out infinite',
      },
      spacing: { '18': '4.5rem', '88': '22rem', '128': '32rem' },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
